# Upstream reaches into the source directory and includes internal file
# To make a clean separatation, a weired folder structure is created here
# To please the preprocessor's the include path is manipuated

import libs = nlohmann-json-schema-validator%lib{json-schema-validator}
./: exe{json-patch}: cxx{test/json-patch} hxx{src/json-patch} $libs

# Doesn't really matter if we point to src or test -> header file interally
# always looks for ../src/json-patch.hpp. Needs only directory hierarchy
cxx.poptions += "-I$src_base/src"